### PR TITLE
whats a node_modules

### PR DESCRIPTION
**Pull request by SawshaDev**

### CODE REVIEW

**Comment by bedros-p** [comment]
While `npm install` takes care of the dependencies i think this is a better way to do it, for example lets say someone doesnt have a package manager installed, just barebones node for use on a low storage server, this should work out of the box with `node webserver/server.js`

**Comment by SawshaDev** [comment]
shut up

**Comment by bedros-p** [comment]
🤓

**Comment by SawshaDev** [comment]
FUDGE  YOU

**Pull request closed without merging**
